// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyManagerModel;

namespace MoneyManagerModel.Migrations
{
    [DbContext(typeof(ManagerContext))]
    partial class ManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("MoneyManagerModel.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetId");

                    b.HasIndex("UserId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            AssetId = 1,
                            Balance = 5246,
                            Name = "Cash",
                            UserId = 1
                        },
                        new
                        {
                            AssetId = 2,
                            Balance = 87,
                            Name = "Debit cards",
                            UserId = 1
                        },
                        new
                        {
                            AssetId = 3,
                            Balance = 7854,
                            Name = "Bank account",
                            UserId = 1
                        },
                        new
                        {
                            AssetId = 4,
                            Balance = 7846,
                            Name = "Loan",
                            UserId = 1
                        },
                        new
                        {
                            AssetId = 5,
                            Balance = 8974,
                            Name = "Cash",
                            UserId = 2
                        },
                        new
                        {
                            AssetId = 6,
                            Balance = 987,
                            Name = "Debit cards",
                            UserId = 2
                        },
                        new
                        {
                            AssetId = 7,
                            Balance = 568,
                            Name = "Bank account",
                            UserId = 2
                        },
                        new
                        {
                            AssetId = 8,
                            Balance = 230495,
                            Name = "Loan",
                            UserId = 2
                        },
                        new
                        {
                            AssetId = 9,
                            Balance = 6575,
                            Name = "Cash",
                            UserId = 3
                        },
                        new
                        {
                            AssetId = 10,
                            Balance = 165,
                            Name = "Debit cards",
                            UserId = 3
                        },
                        new
                        {
                            AssetId = 11,
                            Balance = 8945,
                            Name = "Bank account",
                            UserId = 3
                        },
                        new
                        {
                            AssetId = 12,
                            Balance = 25778,
                            Name = "Bank account",
                            UserId = 3
                        },
                        new
                        {
                            AssetId = 13,
                            Balance = 2656,
                            Name = "Cash",
                            UserId = 4
                        },
                        new
                        {
                            AssetId = 14,
                            Balance = 3526,
                            Name = "Loan",
                            UserId = 4
                        },
                        new
                        {
                            AssetId = 15,
                            Balance = 87986,
                            Name = "Bank account",
                            UserId = 4
                        },
                        new
                        {
                            AssetId = 16,
                            Balance = 31645,
                            Name = "Loan",
                            UserId = 4
                        },
                        new
                        {
                            AssetId = 17,
                            Balance = 56,
                            Name = "Cash",
                            UserId = 5
                        },
                        new
                        {
                            AssetId = 18,
                            Balance = 2566,
                            Name = "Debit cards",
                            UserId = 5
                        },
                        new
                        {
                            AssetId = 19,
                            Balance = 5254,
                            Name = "Bank account",
                            UserId = 5
                        },
                        new
                        {
                            AssetId = 20,
                            Balance = 8787,
                            Name = "Loan",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("MoneyManagerModel.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Color")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2309453);

                    b.Property<bool>("IsIncome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Color = 2309453,
                            IsIncome = true,
                            Name = "Salary"
                        },
                        new
                        {
                            CategoryId = 2,
                            Color = 2309453,
                            IsIncome = true,
                            Name = "Bonus"
                        },
                        new
                        {
                            CategoryId = 3,
                            Color = 2309453,
                            IsIncome = true,
                            Name = "Petty cash"
                        },
                        new
                        {
                            CategoryId = 4,
                            Color = 2309453,
                            IsIncome = false,
                            Name = "Food"
                        },
                        new
                        {
                            CategoryId = 5,
                            Color = 2309453,
                            IsIncome = false,
                            Name = "Social Life"
                        },
                        new
                        {
                            CategoryId = 6,
                            Color = 2309453,
                            IsIncome = false,
                            Name = "Self-development"
                        },
                        new
                        {
                            CategoryId = 7,
                            Color = 2309453,
                            IsIncome = false,
                            Name = "Culture"
                        },
                        new
                        {
                            CategoryId = 8,
                            Color = 2309453,
                            IsIncome = false,
                            Name = "Transportation"
                        },
                        new
                        {
                            CategoryId = 9,
                            Color = 2309453,
                            IsIncome = false,
                            Name = "Public transport",
                            ParentId = 8
                        },
                        new
                        {
                            CategoryId = 10,
                            Color = 2309453,
                            IsIncome = false,
                            Name = "Taxi",
                            ParentId = 8
                        });
                });

            modelBuilder.Entity("MoneyManagerModel.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("AssetId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            Amount = 56,
                            AssetId = 1,
                            CategoryId = 1,
                            Comment = "MusicGlobal",
                            Date = new DateTime(2021, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 2,
                            Amount = 14,
                            AssetId = 2,
                            CategoryId = 1,
                            Comment = "ElementSquare",
                            Date = new DateTime(2021, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 3,
                            Amount = 77,
                            AssetId = 3,
                            CategoryId = 1,
                            Comment = "DollGlobal",
                            Date = new DateTime(2021, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 4,
                            Amount = 90,
                            AssetId = 4,
                            CategoryId = 1,
                            Comment = "PrioritySquare",
                            Date = new DateTime(2020, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 5,
                            Amount = 439,
                            AssetId = 5,
                            CategoryId = 1,
                            Comment = "ChefMusic",
                            Date = new DateTime(2020, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 6,
                            Amount = 521,
                            AssetId = 6,
                            CategoryId = 1,
                            Comment = "SundayTops",
                            Date = new DateTime(2020, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 7,
                            Amount = 547,
                            AssetId = 7,
                            CategoryId = 1,
                            Comment = "Tonlaron",
                            Date = new DateTime(2020, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 8,
                            Amount = 992,
                            AssetId = 8,
                            CategoryId = 1,
                            Comment = "Rokataron",
                            Date = new DateTime(2021, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 9,
                            Amount = 23,
                            AssetId = 9,
                            CategoryId = 1,
                            Comment = "Ronpha",
                            Date = new DateTime(2020, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 10,
                            Amount = 565,
                            AssetId = 10,
                            CategoryId = 1,
                            Comment = "SnowflakesGem",
                            Date = new DateTime(2020, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 11,
                            Amount = 54,
                            AssetId = 11,
                            CategoryId = 2,
                            Comment = "TheaterCompass",
                            Date = new DateTime(2021, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 12,
                            Amount = 448,
                            AssetId = 12,
                            CategoryId = 2,
                            Comment = "Carouselot",
                            Date = new DateTime(2020, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 13,
                            Amount = 126,
                            AssetId = 13,
                            CategoryId = 2,
                            Comment = "SundayTops",
                            Date = new DateTime(2020, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 14,
                            Amount = 843,
                            AssetId = 14,
                            CategoryId = 2,
                            Comment = "KnightForward",
                            Date = new DateTime(2020, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 15,
                            Amount = 231,
                            AssetId = 15,
                            CategoryId = 2,
                            Comment = "TheaterCompass",
                            Date = new DateTime(2020, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 16,
                            Amount = 108,
                            AssetId = 16,
                            CategoryId = 2,
                            Comment = "Tonlaron",
                            Date = new DateTime(2020, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 17,
                            Amount = 977,
                            AssetId = 17,
                            CategoryId = 2,
                            Comment = "ElementSquare",
                            Date = new DateTime(2021, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 18,
                            Amount = 168,
                            AssetId = 18,
                            CategoryId = 2,
                            Comment = "ChefMusic",
                            Date = new DateTime(2020, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 19,
                            Amount = 294,
                            AssetId = 19,
                            CategoryId = 2,
                            Comment = "SundayTops",
                            Date = new DateTime(2020, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 20,
                            Amount = 388,
                            AssetId = 20,
                            CategoryId = 2,
                            Comment = "Carouselot",
                            Date = new DateTime(2020, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 21,
                            Amount = 864,
                            AssetId = 1,
                            CategoryId = 3,
                            Comment = "Rokataron",
                            Date = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 22,
                            Amount = 539,
                            AssetId = 2,
                            CategoryId = 3,
                            Comment = "TheaterCompass",
                            Date = new DateTime(2020, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 23,
                            Amount = 187,
                            AssetId = 3,
                            CategoryId = 3,
                            Comment = "SnowflakesGem",
                            Date = new DateTime(2020, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 24,
                            Amount = 815,
                            AssetId = 4,
                            CategoryId = 3,
                            Comment = "ElementSquare",
                            Date = new DateTime(2021, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 25,
                            Amount = 967,
                            AssetId = 5,
                            CategoryId = 3,
                            Comment = "Tonlaron",
                            Date = new DateTime(2021, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 26,
                            Amount = 208,
                            AssetId = 6,
                            CategoryId = 3,
                            Comment = "SundayTops",
                            Date = new DateTime(2020, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 27,
                            Amount = 670,
                            AssetId = 7,
                            CategoryId = 3,
                            Comment = "Carouselot",
                            Date = new DateTime(2020, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 28,
                            Amount = 290,
                            AssetId = 8,
                            CategoryId = 3,
                            Comment = "ChefMusic",
                            Date = new DateTime(2020, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 29,
                            Amount = 668,
                            AssetId = 9,
                            CategoryId = 3,
                            Comment = "TheaterCompass",
                            Date = new DateTime(2021, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 30,
                            Amount = 533,
                            AssetId = 10,
                            CategoryId = 3,
                            Comment = "Rokataron",
                            Date = new DateTime(2020, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 31,
                            Amount = 969,
                            AssetId = 11,
                            CategoryId = 4,
                            Comment = "Carouselot",
                            Date = new DateTime(2020, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 32,
                            Amount = 889,
                            AssetId = 12,
                            CategoryId = 4,
                            Comment = "Tonlaron",
                            Date = new DateTime(2020, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 33,
                            Amount = 819,
                            AssetId = 13,
                            CategoryId = 4,
                            Comment = "SnowflakesGem",
                            Date = new DateTime(2020, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 34,
                            Amount = 127,
                            AssetId = 14,
                            CategoryId = 4,
                            Comment = "KnightForward",
                            Date = new DateTime(2020, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 35,
                            Amount = 136,
                            AssetId = 15,
                            CategoryId = 4,
                            Comment = "Tonlaron",
                            Date = new DateTime(2020, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 36,
                            Amount = 821,
                            AssetId = 16,
                            CategoryId = 4,
                            Comment = "ElementSquare",
                            Date = new DateTime(2020, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 37,
                            Amount = 752,
                            AssetId = 17,
                            CategoryId = 4,
                            Comment = "KnightForward",
                            Date = new DateTime(2020, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 38,
                            Amount = 592,
                            AssetId = 18,
                            CategoryId = 4,
                            Comment = "SundayTops",
                            Date = new DateTime(2021, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 39,
                            Amount = 693,
                            AssetId = 19,
                            CategoryId = 4,
                            Comment = "SnowflakesGem",
                            Date = new DateTime(2021, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 40,
                            Amount = 902,
                            AssetId = 20,
                            CategoryId = 4,
                            Comment = "ChefMusic",
                            Date = new DateTime(2021, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 41,
                            Amount = 214,
                            AssetId = 1,
                            CategoryId = 5,
                            Comment = "Tonlaron",
                            Date = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 42,
                            Amount = 32,
                            AssetId = 2,
                            CategoryId = 5,
                            Comment = "Phamiron",
                            Date = new DateTime(2020, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 43,
                            Amount = 579,
                            AssetId = 3,
                            CategoryId = 5,
                            Comment = "Larokata",
                            Date = new DateTime(2020, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 44,
                            Amount = 305,
                            AssetId = 4,
                            CategoryId = 5,
                            Comment = "RobustArrakis",
                            Date = new DateTime(2020, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 45,
                            Amount = 554,
                            AssetId = 5,
                            CategoryId = 5,
                            Comment = "RobustArrakis",
                            Date = new DateTime(2020, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 46,
                            Amount = 838,
                            AssetId = 6,
                            CategoryId = 5,
                            Comment = "Carouselot",
                            Date = new DateTime(2020, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 47,
                            Amount = 673,
                            AssetId = 7,
                            CategoryId = 5,
                            Comment = "Rokataron",
                            Date = new DateTime(2020, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 48,
                            Amount = 533,
                            AssetId = 8,
                            CategoryId = 5,
                            Comment = "Tonlaron",
                            Date = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 49,
                            Amount = 299,
                            AssetId = 9,
                            CategoryId = 5,
                            Comment = "SundayTops",
                            Date = new DateTime(2020, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 50,
                            Amount = 184,
                            AssetId = 10,
                            CategoryId = 5,
                            Comment = "Larokata",
                            Date = new DateTime(2020, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 51,
                            Amount = 355,
                            AssetId = 11,
                            CategoryId = 6,
                            Comment = "Phamiron",
                            Date = new DateTime(2021, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 52,
                            Amount = 614,
                            AssetId = 12,
                            CategoryId = 6,
                            Comment = "RobustArrakis",
                            Date = new DateTime(2020, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 53,
                            Amount = 442,
                            AssetId = 13,
                            CategoryId = 6,
                            Comment = "Carouselot",
                            Date = new DateTime(2020, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 54,
                            Amount = 955,
                            AssetId = 14,
                            CategoryId = 6,
                            Comment = "ElementSquare",
                            Date = new DateTime(2020, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 55,
                            Amount = 264,
                            AssetId = 15,
                            CategoryId = 6,
                            Comment = "Tonlaron",
                            Date = new DateTime(2020, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 56,
                            Amount = 420,
                            AssetId = 16,
                            CategoryId = 6,
                            Comment = "Larokata",
                            Date = new DateTime(2020, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 57,
                            Amount = 766,
                            AssetId = 17,
                            CategoryId = 6,
                            Comment = "Phamiron",
                            Date = new DateTime(2020, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 58,
                            Amount = 625,
                            AssetId = 18,
                            CategoryId = 6,
                            Comment = "KnightForward",
                            Date = new DateTime(2020, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 59,
                            Amount = 609,
                            AssetId = 19,
                            CategoryId = 6,
                            Comment = "ChefMusic",
                            Date = new DateTime(2020, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 60,
                            Amount = 599,
                            AssetId = 20,
                            CategoryId = 6,
                            Comment = "Tonlaron",
                            Date = new DateTime(2020, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 61,
                            Amount = 972,
                            AssetId = 1,
                            CategoryId = 7,
                            Comment = "ElementSquare",
                            Date = new DateTime(2020, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 62,
                            Amount = 880,
                            AssetId = 2,
                            CategoryId = 7,
                            Comment = "Rokataron",
                            Date = new DateTime(2020, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 63,
                            Amount = 356,
                            AssetId = 3,
                            CategoryId = 7,
                            Comment = "SundayTops",
                            Date = new DateTime(2020, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 64,
                            Amount = 210,
                            AssetId = 4,
                            CategoryId = 7,
                            Comment = "TheaterCompass",
                            Date = new DateTime(2020, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 65,
                            Amount = 651,
                            AssetId = 5,
                            CategoryId = 7,
                            Comment = "SnowflakesGem",
                            Date = new DateTime(2020, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 66,
                            Amount = 753,
                            AssetId = 6,
                            CategoryId = 7,
                            Comment = "RobustArrakis",
                            Date = new DateTime(2020, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 67,
                            Amount = 269,
                            AssetId = 7,
                            CategoryId = 7,
                            Comment = "KnightForward",
                            Date = new DateTime(2020, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 68,
                            Amount = 612,
                            AssetId = 8,
                            CategoryId = 7,
                            Comment = "Tonlaron",
                            Date = new DateTime(2020, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 69,
                            Amount = 461,
                            AssetId = 9,
                            CategoryId = 7,
                            Comment = "RobustArrakis",
                            Date = new DateTime(2020, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 70,
                            Amount = 175,
                            AssetId = 10,
                            CategoryId = 7,
                            Comment = "SundayTops",
                            Date = new DateTime(2020, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 71,
                            Amount = 40,
                            AssetId = 11,
                            CategoryId = 8,
                            Comment = "ElementSquare",
                            Date = new DateTime(2020, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 72,
                            Amount = 773,
                            AssetId = 12,
                            CategoryId = 8,
                            Comment = "Larokata",
                            Date = new DateTime(2020, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 73,
                            Amount = 259,
                            AssetId = 13,
                            CategoryId = 8,
                            Comment = "Rokataron",
                            Date = new DateTime(2021, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 74,
                            Amount = 674,
                            AssetId = 14,
                            CategoryId = 8,
                            Comment = "KnightForward",
                            Date = new DateTime(2021, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 75,
                            Amount = 703,
                            AssetId = 15,
                            CategoryId = 8,
                            Comment = "Tonlaron",
                            Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 76,
                            Amount = 551,
                            AssetId = 16,
                            CategoryId = 8,
                            Comment = "MatCoast",
                            Date = new DateTime(2020, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 77,
                            Amount = 499,
                            AssetId = 17,
                            CategoryId = 8,
                            Comment = "MatCoast",
                            Date = new DateTime(2020, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 78,
                            Amount = 989,
                            AssetId = 18,
                            CategoryId = 8,
                            Comment = "ChefMusic",
                            Date = new DateTime(2021, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 79,
                            Amount = 132,
                            AssetId = 19,
                            CategoryId = 8,
                            Comment = "TheaterCompass",
                            Date = new DateTime(2020, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 80,
                            Amount = 24,
                            AssetId = 20,
                            CategoryId = 8,
                            Comment = "SundayTops",
                            Date = new DateTime(2020, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 81,
                            Amount = 788,
                            AssetId = 1,
                            CategoryId = 9,
                            Comment = "KnightForward",
                            Date = new DateTime(2020, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 82,
                            Amount = 186,
                            AssetId = 2,
                            CategoryId = 9,
                            Comment = "ChefMusic",
                            Date = new DateTime(2020, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 83,
                            Amount = 635,
                            AssetId = 3,
                            CategoryId = 9,
                            Comment = "Tonlaron",
                            Date = new DateTime(2020, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 84,
                            Amount = 465,
                            AssetId = 4,
                            CategoryId = 9,
                            Comment = "SnowflakesGem",
                            Date = new DateTime(2020, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 85,
                            Amount = 1839,
                            AssetId = 5,
                            CategoryId = 9,
                            Comment = "Phamiron",
                            Date = new DateTime(2020, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 86,
                            Amount = 1621,
                            AssetId = 6,
                            CategoryId = 9,
                            Comment = "Carouselot",
                            Date = new DateTime(2020, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 87,
                            Amount = 474,
                            AssetId = 7,
                            CategoryId = 9,
                            Comment = "Larokata",
                            Date = new DateTime(2020, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 88,
                            Amount = 519,
                            AssetId = 8,
                            CategoryId = 9,
                            Comment = "TheaterCompass",
                            Date = new DateTime(2020, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 89,
                            Amount = 170,
                            AssetId = 9,
                            CategoryId = 9,
                            Comment = "Tonlaron",
                            Date = new DateTime(2020, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 90,
                            Amount = 1129,
                            AssetId = 10,
                            CategoryId = 9,
                            Comment = "Carouselot",
                            Date = new DateTime(2020, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 91,
                            Amount = 1290,
                            AssetId = 11,
                            CategoryId = 10,
                            Comment = "SundayTops",
                            Date = new DateTime(2020, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 92,
                            Amount = 146,
                            AssetId = 12,
                            CategoryId = 10,
                            Comment = "KnightForward",
                            Date = new DateTime(2020, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 93,
                            Amount = 1273,
                            AssetId = 13,
                            CategoryId = 10,
                            Comment = "Rokataron",
                            Date = new DateTime(2020, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 94,
                            Amount = 298,
                            AssetId = 14,
                            CategoryId = 10,
                            Comment = "ChefMusic",
                            Date = new DateTime(2020, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 95,
                            Amount = 1166,
                            AssetId = 15,
                            CategoryId = 10,
                            Comment = "TheaterCompass",
                            Date = new DateTime(2021, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 96,
                            Amount = 639,
                            AssetId = 16,
                            CategoryId = 10,
                            Comment = "Tonlaron",
                            Date = new DateTime(2020, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 97,
                            Amount = 789,
                            AssetId = 17,
                            CategoryId = 10,
                            Comment = "MatCoast",
                            Date = new DateTime(2020, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 98,
                            Amount = 706,
                            AssetId = 18,
                            CategoryId = 10,
                            Comment = "Phamiron",
                            Date = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 99,
                            Amount = 1123,
                            AssetId = 19,
                            CategoryId = 10,
                            Comment = "ElementSquare",
                            Date = new DateTime(2020, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 100,
                            Amount = 160,
                            AssetId = 20,
                            CategoryId = 10,
                            Comment = "SnowflakesGem",
                            Date = new DateTime(2020, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MoneyManagerModel.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "ClydeETroia@dayrep.com",
                            Name = "Clyde E. Troia"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "DanielDFleischer@armyspy.com",
                            Name = "Daniel D. Fleischer"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "RichardNParsons@dayrep.com",
                            Name = "Richard N. Parsons"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "JamesLPonce@teleworm.us",
                            Name = "James L. Ponce"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "LauraJBancroft@rhyta.com",
                            Name = "Laura J. Bancroft"
                        });
                });

            modelBuilder.Entity("MoneyManagerModel.Asset", b =>
                {
                    b.HasOne("MoneyManagerModel.User", "User")
                        .WithMany("Assets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyManagerModel.Category", b =>
                {
                    b.HasOne("MoneyManagerModel.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MoneyManagerModel.Transaction", b =>
                {
                    b.HasOne("MoneyManagerModel.Asset", "Asset")
                        .WithMany("Transactions")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyManagerModel.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MoneyManagerModel.Asset", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MoneyManagerModel.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MoneyManagerModel.User", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
